FROM vcmelodic_dev_overlay:latest

# Dev Env
RUN echo "source /workspaces/catkin_ws/devel/setup.bash" >> ~/.bashrc
RUN echo "source /workspaces/catkin_ws/devel/setup.bash" >> /home/vscode/.bashrc
RUN echo "echo loading /workspaces/catkin_ws/devel/setup.bash" >> ~/.bashrc
RUN echo "echo loading /workspaces/catkin_ws/devel/setup.bash" >> /home/vscode/.bashrc
