FROM vcfoxy_dev_overlay:latest

# Dev Env
RUN echo "source /workspaces/my_workspace/devel/setup.bash" >> ~/.bashrc
RUN echo "source /workspaces/my_workspace/devel/setup.bash" >> /home/vscode/.bashrc
RUN echo "echo loading /workspaces/my_workspace/devel/setup.bash" >> ~/.bashrc
RUN echo "echo loading /workspaces/my_workspace/devel/setup.bash" >> /home/vscode/.bashrc
